import { todayIso } from "./date";
import type { Snapshot } from "../types";

const today = todayIso();
const demoHouseholdId = crypto.randomUUID();
const demoPatientGrandfatherId = crypto.randomUUID();
const demoPatientGrandmotherId = crypto.randomUUID();
const demoMedicineMetforminId = crypto.randomUUID();
const demoMedicineAtorvastatinId = crypto.randomUUID();
const demoPurchaseId = crypto.randomUUID();
const demoReportId = crypto.randomUUID();
const demoDailyLogId = crypto.randomUUID();

export const demoSnapshot: Snapshot = {
  household: {
    id: demoHouseholdId,
    owner_id: "demo-user",
    name: "Family Health Ledger",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  patients: [
    {
      id: demoPatientGrandfatherId,
      household_id: demoHouseholdId,
      name: "Grandfather",
      relationship: "Patient",
      birth_year: 1948,
      conditions: "Diabetes, blood pressure",
      notes: "Prefers morning checks and clear labels on medicine timing.",
      color_accent: "#f97316",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: demoPatientGrandmotherId,
      household_id: demoHouseholdId,
      name: "Grandmother",
      relationship: "Patient",
      birth_year: 1952,
      conditions: "Cholesterol, thyroid",
      notes: "Family uploads most reports from her phone after clinic visits.",
      color_accent: "#14b8a6",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  medicines: [
    {
      id: demoMedicineMetforminId,
      household_id: demoHouseholdId,
      patient_id: demoPatientGrandfatherId,
      name: "Metformin 500mg",
      purpose: "Diabetes control",
      dosage_per_day: 2,
      schedule: ["Morning", "Evening"],
      timing_slots: {
        after_breakfast: "1 tablet",
        after_dinner: "1 tablet",
      },
      specific_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      specific_times: ["08:30", "20:30"],
      duration_days: null,
      dosage_notes: "Take after food only.",
      tablets_per_strip: 15,
      initial_strips_bought: 1,
      initial_total_cost: 75,
      start_date: today,
      stop_date: null,
      notes: "Main sugar medicine.",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: demoMedicineAtorvastatinId,
      household_id: demoHouseholdId,
      patient_id: demoPatientGrandmotherId,
      name: "Atorvastatin 10mg",
      purpose: "Cholesterol support",
      dosage_per_day: 1,
      schedule: ["Night"],
      timing_slots: {
        after_dinner: "1 tablet",
      },
      specific_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      specific_times: ["21:00"],
      duration_days: null,
      dosage_notes: "Night dose only.",
      tablets_per_strip: 10,
      initial_strips_bought: 2,
      initial_total_cost: 180,
      start_date: today,
      stop_date: null,
      notes: "Keep continuous unless doctor stops it.",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  purchases: [
    {
      id: demoPurchaseId,
      household_id: demoHouseholdId,
      patient_id: demoPatientGrandfatherId,
      medicine_id: demoMedicineMetforminId,
      label: "Metformin refill",
      purchased_on: today,
      strips_bought: 2,
      tablets_per_strip: 15,
      total_cost: 150,
      pharmacy: "Local pharmacy",
      notes: "Bought two strips.",
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  reports: [
    {
      id: demoReportId,
      household_id: demoHouseholdId,
      patient_id: demoPatientGrandmotherId,
      title: "Quarterly lipid panel",
      report_type: "Lab report",
      report_date: today,
      summary: "Track LDL and thyroid before the next visit.",
      file_url: "",
      file_path: "",
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  dailyLogs: [
    {
      id: demoDailyLogId,
      household_id: demoHouseholdId,
      patient_id: demoPatientGrandfatherId,
      logged_on: today,
      bp_systolic: 128,
      bp_diastolic: 82,
      pulse: 76,
      sugar: 136,
      temperature: 98.4,
      weight: 67,
      notes: "Morning reading after breakfast.",
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
