import { todayIso } from "./date";
import type { Snapshot } from "../types";

const today = todayIso();

export const demoSnapshot: Snapshot = {
  household: {
    id: "demo-household",
    owner_id: "demo-user",
    name: "Family Health Ledger",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  patients: [
    {
      id: "p-grandfather",
      household_id: "demo-household",
      name: "Grandfather",
      relationship: "Patient",
      birth_year: 1948,
      conditions: "Diabetes, blood pressure",
      notes: "Prefers morning stock checks.",
      color_accent: "#f97316",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p-grandmother",
      household_id: "demo-household",
      name: "Grandmother",
      relationship: "Patient",
      birth_year: 1952,
      conditions: "Cholesterol, thyroid",
      notes: "Lab reports usually arrive on WhatsApp PDF.",
      color_accent: "#14b8a6",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  medicines: [
    {
      id: "m-metformin",
      household_id: "demo-household",
      patient_id: "p-grandfather",
      name: "Metformin 500mg",
      purpose: "Diabetes control",
      dosage_per_day: 2,
      schedule: ["Morning", "Evening"],
      tablets_per_strip: 15,
      initial_strips_bought: 1,
      initial_total_cost: 75,
      start_date: today,
      stop_date: null,
      notes: "Take after food.",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "m-atorvastatin",
      household_id: "demo-household",
      patient_id: "p-grandmother",
      name: "Atorvastatin 10mg",
      purpose: "Cholesterol support",
      dosage_per_day: 1,
      schedule: ["Night"],
      tablets_per_strip: 10,
      initial_strips_bought: 2,
      initial_total_cost: 180,
      start_date: today,
      stop_date: null,
      notes: "Night dose only.",
      is_active: true,
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  purchases: [
    {
      id: "buy-metformin",
      household_id: "demo-household",
      patient_id: "p-grandfather",
      medicine_id: "m-metformin",
      label: "Metformin refill",
      purchased_on: today,
      strips_bought: 2,
      tablets_per_strip: 15,
      total_cost: 150,
      pharmacy: "Local pharmacy",
      notes: "Bought two strips.",
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "buy-atorvastatin",
      household_id: "demo-household",
      patient_id: "p-grandmother",
      medicine_id: "m-atorvastatin",
      label: "Atorvastatin refill",
      purchased_on: today,
      strips_bought: 1,
      tablets_per_strip: 10,
      total_cost: 90,
      pharmacy: "Clinic pharmacy",
      notes: "",
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  reports: [
    {
      id: "r-demo",
      household_id: "demo-household",
      patient_id: "p-grandmother",
      title: "Quarterly lipid panel",
      report_type: "Lab report",
      report_date: today,
      summary: "Track LDL and thyroid before the next visit.",
      file_url: "",
      file_path: "",
      is_archived: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
